# Generated by Django 5.2.12 on 2026-07-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_partyannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('secretary', 'Secretary'), ('vice_president', 'Vice President')], default='member', max_length=20),
        ),
    ]
