# Generated by Django 5.2.12 on 2026-06-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reel_reelcomment_reellike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='media',
            field=models.FileField(upload_to='reels/'),
        ),
    ]
