# Generated by Django 5.2.12 on 2026-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_media_type_alter_post_post_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
